import type { Inspection, ReportStatus, ReviewStatus, RiskLevel } from './inspection-types'

const IMG = {
  dent: '/containers/container-dent.png',
  rust: '/containers/container-rust.png',
  hole: '/containers/container-hole.png',
  clean: '/containers/container-clean.png',
}

type Tone = 'destructive' | 'warning' | 'info' | 'success' | 'muted'

export const STATUS_META: Record<ReviewStatus, { label: string; tone: Tone }> = {
  PENDING_CLOUD_ANALYSIS: { label: '분석 중', tone: 'info' },
  MANUAL_NEEDED: { label: '수동 검수 필요', tone: 'destructive' },
  AUDIT_REQUIRED: { label: '랜덤 감사 대상', tone: 'warning' },
  AUTO_OK: { label: '자동 승인', tone: 'success' },
  DONE: { label: '검수 완료', tone: 'muted' },
  REPORT_PENDING: { label: '보고서 생성 대기', tone: 'info' },
  REPORT_CREATED: { label: '보고서 생성 완료', tone: 'success' },
  INFERENCE_FAILED: { label: '처리 실패', tone: 'destructive' },
}

export const RISK_META: Record<RiskLevel, { label: string; tone: 'destructive' | 'warning' | 'success' }> = {
  HIGH: { label: '높음', tone: 'destructive' },
  MEDIUM: { label: '보통', tone: 'warning' },
  LOW: { label: '낮음', tone: 'success' },
}

export const REPORT_META: Record<ReportStatus, { label: string; tone: Tone }> = {
  PENDING: { label: '생성 대기', tone: 'muted' },
  GENERATING: { label: '생성 중', tone: 'info' },
  GENERATED: { label: '생성 완료', tone: 'success' },
  COMPLETED: { label: '완료', tone: 'success' },
  FAILED: { label: '생성 실패', tone: 'destructive' },
}

export const SEVERITY_LABEL: Record<RiskLevel, string> = {
  HIGH: '높음',
  MEDIUM: '보통',
  LOW: '낮음',
}

export const mockInspections: Inspection[] = [
  {
    event_id: 'INS-4821',
    container_id: 'MSKU 774213-6',
    captured_at: '2026-07-13T08:42:00Z',
    damage_summary: '측면 패널 관통 및 찢김',
    risk_score: 94,
    risk_level: 'HIGH',
    review_status: 'MANUAL_NEEDED',
    raw_image_url: IMG.hole,
    assigned_inspector: '담당자 미지정',
    ai_summary: '측면 패널에서 관통 손상과 금속 찢김이 동시에 확인되었습니다. 구조적 위험이 높아 즉시 수동 검수가 필요합니다.',
    verdict: '수동 정밀 검수 필요',
    detections: [
      { id: 'd1', label: '관통', confidence: 0.97, severity: 'HIGH', description: '측면 패널 중앙부에 완전 관통된 구멍이 감지되었습니다.', box: { x: 41, y: 38, width: 20, height: 22 } },
      { id: 'd2', label: '금속 찢김', confidence: 0.89, severity: 'HIGH', description: '관통부 주변으로 금속이 찢겨 날카로운 모서리가 형성되었습니다.', box: { x: 34, y: 30, width: 34, height: 38 } },
      { id: 'd3', label: '표면 긁힘', confidence: 0.74, severity: 'MEDIUM', description: '하단 좌측에 다수의 긁힘 자국이 확인됩니다.', box: { x: 12, y: 58, width: 18, height: 12 } },
    ],
    ocr: { text: 'MSKU 774213-6', confidence: 0.93, matches_manifest: true },
    report_status: 'PENDING',
  },
  {
    event_id: 'INS-4818',
    container_id: 'TCLU 550918-2',
    captured_at: '2026-07-13T08:31:00Z',
    damage_summary: '엔드 패널 대형 찌그러짐',
    risk_score: 88,
    risk_level: 'HIGH',
    review_status: 'MANUAL_NEEDED',
    raw_image_url: IMG.dent,
    assigned_inspector: '담당자 미지정',
    ai_summary: '엔드 패널에 대형 구조적 찌그러짐과 코너 변형이 확인되었습니다. 적재 안정성 확인이 필요합니다.',
    verdict: '수동 정밀 검수 필요',
    detections: [
      { id: 'd1', label: '구조적 찌그러짐', confidence: 0.95, severity: 'HIGH', description: '엔드 패널 중앙이 안쪽으로 크게 함몰되었습니다.', box: { x: 30, y: 28, width: 40, height: 42 } },
      { id: 'd2', label: '코너 변형', confidence: 0.81, severity: 'MEDIUM', description: '우측 하단 코너 캐스팅에 변형이 감지됩니다.', box: { x: 62, y: 60, width: 20, height: 20 } },
    ],
    ocr: { text: 'TCLU 550918-2', confidence: 0.9, matches_manifest: true },
    report_status: 'PENDING',
  },
  {
    event_id: 'INS-4830',
    container_id: 'KKFU 118920-3',
    captured_at: '2026-07-13T08:49:00Z',
    damage_summary: '분석 진행 중',
    risk_score: 0,
    risk_level: 'LOW',
    review_status: 'PENDING_CLOUD_ANALYSIS',
    raw_image_url: IMG.clean,
    assigned_inspector: '담당자 미지정',
    ai_summary: '',
    verdict: '',
    detections: [],
    ocr: { text: 'KKFU 118920-3', confidence: 0.0, matches_manifest: false },
    report_status: 'PENDING',
  },
  {
    event_id: 'INS-4829',
    container_id: 'GESU 442071-8',
    captured_at: '2026-07-13T08:47:00Z',
    damage_summary: '분석 진행 중',
    risk_score: 0,
    risk_level: 'LOW',
    review_status: 'PENDING_CLOUD_ANALYSIS',
    raw_image_url: IMG.clean,
    assigned_inspector: '담당자 미지정',
    ai_summary: '',
    verdict: '',
    detections: [],
    ocr: { text: 'GESU 442071-8', confidence: 0.0, matches_manifest: false },
    report_status: 'PENDING',
  },
  {
    event_id: 'INS-4805',
    container_id: 'HLXU 209471-0',
    captured_at: '2026-07-13T08:05:00Z',
    damage_summary: '도어 실링부 심한 부식',
    risk_score: 79,
    risk_level: 'HIGH',
    review_status: 'AUDIT_REQUIRED',
    raw_image_url: IMG.rust,
    assigned_inspector: '오카포르',
    ai_summary: '도어 실링부를 따라 심한 부식 군집과 도장 박리가 확인됩니다. 밀폐 성능 저하 가능성이 있습니다.',
    verdict: '감사 검토 권장',
    detections: [
      { id: 'd1', label: '부식 군집', confidence: 0.88, severity: 'HIGH', description: '도어 실링부를 따라 넓은 범위의 부식이 진행되었습니다.', box: { x: 55, y: 20, width: 26, height: 52 } },
      { id: 'd2', label: '도장 박리', confidence: 0.72, severity: 'MEDIUM', description: '좌측 패널의 도장이 벗겨져 금속이 노출되었습니다.', box: { x: 20, y: 40, width: 22, height: 30 } },
    ],
    ocr: { text: 'HLXU 209471-0', confidence: 0.86, matches_manifest: false },
    report_status: 'PENDING',
  },
  {
    event_id: 'INS-4799',
    container_id: 'OOLU 118253-4',
    captured_at: '2026-07-13T07:52:00Z',
    damage_summary: '찌그러짐 및 표면 긁힘',
    risk_score: 66,
    risk_level: 'MEDIUM',
    review_status: 'AUDIT_REQUIRED',
    raw_image_url: IMG.dent,
    assigned_inspector: '오카포르',
    ai_summary: '중간 규모의 찌그러짐과 경미한 긁힘이 확인됩니다. 구조적 위험은 낮으나 감사 대상으로 분류되었습니다.',
    verdict: '감사 검토 권장',
    detections: [
      { id: 'd1', label: '찌그러짐', confidence: 0.83, severity: 'MEDIUM', description: '패널 중앙부에 중간 깊이의 찌그러짐이 있습니다.', box: { x: 36, y: 34, width: 30, height: 30 } },
      { id: 'd2', label: '긁힘', confidence: 0.69, severity: 'LOW', description: '하단부에 경미한 긁힘이 확인됩니다.', box: { x: 15, y: 62, width: 22, height: 12 } },
    ],
    ocr: { text: 'OOLU 118253-4', confidence: 0.91, matches_manifest: true },
    report_status: 'PENDING',
  },
  {
    event_id: 'INS-4714',
    container_id: 'WHLU 634418-9',
    captured_at: '2026-07-13T05:26:00Z',
    damage_summary: '찌그러짐 및 부식',
    risk_score: 83,
    risk_level: 'HIGH',
    review_status: 'AUDIT_REQUIRED',
    raw_image_url: IMG.dent,
    assigned_inspector: '오카포르',
    ai_summary: '찌그러짐과 부식이 함께 확인되며 컨테이너 번호가 매니페스트와 불일치합니다. 수동 확인이 권장됩니다.',
    verdict: '감사 검토 권장',
    detections: [
      { id: 'd1', label: '찌그러짐', confidence: 0.86, severity: 'HIGH', description: '엔드 패널에 큰 찌그러짐이 감지되었습니다.', box: { x: 32, y: 30, width: 34, height: 34 } },
      { id: 'd2', label: '부식', confidence: 0.77, severity: 'MEDIUM', description: '우측 하단에 부식 진행 흔적이 확인됩니다.', box: { x: 60, y: 55, width: 22, height: 22 } },
    ],
    ocr: { text: 'WHLU 634418-9', confidence: 0.85, matches_manifest: false },
    report_status: 'PENDING',
  },
  {
    event_id: 'INS-4790',
    container_id: 'CMAU 663017-9',
    captured_at: '2026-07-13T07:40:00Z',
    damage_summary: '하단 패널 녹 자국',
    risk_score: 58,
    risk_level: 'MEDIUM',
    review_status: 'REPORT_PENDING',
    raw_image_url: IMG.rust,
    assigned_inspector: '알바레즈',
    ai_summary: '하단 패널을 따라 녹 자국이 확인됩니다. 표면 손상 수준으로 보고서 생성이 진행 중입니다.',
    verdict: '경미 손상 · 보고서 생성',
    detections: [
      { id: 'd1', label: '녹 자국', confidence: 0.8, severity: 'MEDIUM', description: '하단 패널을 가로지르는 녹 흐름 자국이 있습니다.', box: { x: 24, y: 55, width: 48, height: 22 } },
    ],
    ocr: { text: 'CMAU 663017-9', confidence: 0.88, matches_manifest: true },
    report_status: 'GENERATING',
  },
  {
    event_id: 'INS-4782',
    container_id: 'MSCU 401552-3',
    captured_at: '2026-07-13T07:28:00Z',
    damage_summary: '코너 포스트 변형',
    risk_score: 71,
    risk_level: 'HIGH',
    review_status: 'REPORT_PENDING',
    raw_image_url: IMG.hole,
    assigned_inspector: '알바레즈',
    ai_summary: '코너 포스트 변형과 미세 균열이 확인됩니다. 보고서 생성이 진행 중입니다.',
    verdict: '구조 손상 · 보고서 생성',
    detections: [
      { id: 'd1', label: '코너 변형', confidence: 0.85, severity: 'HIGH', description: '상단 우측 코너 포스트가 변형되었습니다.', box: { x: 60, y: 22, width: 24, height: 40 } },
      { id: 'd2', label: '미세 균열', confidence: 0.63, severity: 'MEDIUM', description: '중앙부에 미세한 균열선이 감지됩니다.', box: { x: 40, y: 50, width: 16, height: 14 } },
    ],
    ocr: { text: 'MSCU 401552-3', confidence: 0.84, matches_manifest: true },
    report_status: 'GENERATING',
  },
  {
    event_id: 'INS-4771',
    container_id: 'TGHU 882140-1',
    captured_at: '2026-07-13T07:11:00Z',
    damage_summary: '경미한 흠집 · 구조 위험 없음',
    risk_score: 22,
    risk_level: 'LOW',
    review_status: 'AUTO_OK',
    raw_image_url: IMG.clean,
    assigned_inspector: '자동 처리',
    ai_summary: '표면 흠집만 확인되어 구조적 위험이 없습니다. AI가 자동 승인 처리했습니다.',
    verdict: '자동 승인',
    detections: [
      { id: 'd1', label: '표면 흠집', confidence: 0.66, severity: 'LOW', description: '중앙부에 경미한 표면 흠집이 있습니다.', box: { x: 30, y: 46, width: 18, height: 10 } },
    ],
    ocr: { text: 'TGHU 882140-1', confidence: 0.95, matches_manifest: true },
    report_status: 'PENDING',
  },
  {
    event_id: 'INS-4765',
    container_id: 'APZU 337029-8',
    captured_at: '2026-07-13T06:58:00Z',
    damage_summary: '손상 미검출',
    risk_score: 8,
    risk_level: 'LOW',
    review_status: 'AUTO_OK',
    raw_image_url: IMG.clean,
    assigned_inspector: '자동 처리',
    ai_summary: '감지된 손상이 없습니다. AI가 자동 승인 처리했습니다.',
    verdict: '자동 승인',
    detections: [],
    ocr: { text: 'APZU 337029-8', confidence: 0.97, matches_manifest: true },
    report_status: 'PENDING',
  },
  {
    event_id: 'INS-4722',
    container_id: 'SEGU 271905-4',
    captured_at: '2026-07-13T05:41:00Z',
    damage_summary: '손상 미검출',
    risk_score: 12,
    risk_level: 'LOW',
    review_status: 'AUTO_OK',
    raw_image_url: IMG.clean,
    assigned_inspector: '자동 처리',
    ai_summary: '감지된 손상이 없습니다. AI가 자동 승인 처리했습니다.',
    verdict: '자동 승인',
    detections: [],
    ocr: { text: 'SEGU 271905-4', confidence: 0.96, matches_manifest: true },
    report_status: 'PENDING',
  },
  {
    event_id: 'INS-4758',
    container_id: 'FSCU 720914-5',
    captured_at: '2026-07-13T06:44:00Z',
    damage_summary: '찌그러짐 · 검수 완료',
    risk_score: 61,
    risk_level: 'MEDIUM',
    review_status: 'DONE',
    raw_image_url: IMG.dent,
    assigned_inspector: '오카포르',
    reviewer_comment: '찌그러짐 확인 후 반입 승인함. 구조적 이상 없음.',
    ai_summary: '중간 규모 찌그러짐이 확인되었으며 검수자가 반입을 승인했습니다.',
    verdict: '검수 완료 · 승인',
    detections: [
      { id: 'd1', label: '찌그러짐', confidence: 0.82, severity: 'MEDIUM', description: '패널 중앙부에 중간 깊이의 찌그러짐이 있습니다.', box: { x: 34, y: 32, width: 30, height: 30 } },
    ],
    ocr: { text: 'FSCU 720914-5', confidence: 0.89, matches_manifest: true },
    report_status: 'PENDING',
  },
  {
    event_id: 'INS-4730',
    container_id: 'NYKU 448120-0',
    captured_at: '2026-07-13T05:58:00Z',
    damage_summary: '경미한 녹 · 모니터링',
    risk_score: 39,
    risk_level: 'MEDIUM',
    review_status: 'DONE',
    raw_image_url: IMG.rust,
    assigned_inspector: '알바레즈',
    reviewer_comment: '경미한 녹으로 모니터링 대상 지정 후 반입 승인.',
    ai_summary: '경미한 녹 패치가 확인되어 모니터링 대상으로 처리되었습니다.',
    verdict: '검수 완료 · 승인',
    detections: [
      { id: 'd1', label: '녹 패치', confidence: 0.7, severity: 'MEDIUM', description: '중앙부에 경미한 녹 패치가 있습니다.', box: { x: 40, y: 50, width: 24, height: 18 } },
    ],
    ocr: { text: 'NYKU 448120-0', confidence: 0.9, matches_manifest: true },
    report_status: 'PENDING',
  },
  {
    event_id: 'INS-4749',
    container_id: 'BEAU 156638-7',
    captured_at: '2026-07-13T06:30:00Z',
    damage_summary: '부식 · 보고서 완료',
    risk_score: 74,
    risk_level: 'HIGH',
    review_status: 'REPORT_CREATED',
    raw_image_url: IMG.rust,
    assigned_inspector: '알바레즈',
    reviewer_comment: '부식 범위가 넓어 손상 보고서 제출함. 수리 후 재검토 필요.',
    ai_summary: '넓은 범위의 부식 군집과 도장 박리가 확인되어 손상 보고서가 생성되었습니다.',
    verdict: '손상 확정 · 보고서 제출',
    detections: [
      { id: 'd1', label: '부식 군집', confidence: 0.9, severity: 'HIGH', description: '도어측 패널을 따라 넓은 부식이 진행되었습니다.', box: { x: 50, y: 24, width: 28, height: 48 } },
      { id: 'd2', label: '도장 박리', confidence: 0.71, severity: 'MEDIUM', description: '좌측 패널 도장이 벗겨졌습니다.', box: { x: 18, y: 42, width: 20, height: 26 } },
    ],
    ocr: { text: 'BEAU 156638-7', confidence: 0.87, matches_manifest: true },
    report_status: 'GENERATED',
    report_created_at: '2026-07-13T06:41:00Z',
  },
  {
    event_id: 'INS-4741',
    container_id: 'DFSU 990276-2',
    captured_at: '2026-07-13T06:12:00Z',
    damage_summary: '관통 · 보고서 완료',
    risk_score: 91,
    risk_level: 'HIGH',
    review_status: 'REPORT_CREATED',
    raw_image_url: IMG.hole,
    assigned_inspector: '오카포르',
    reviewer_comment: '관통 및 금속 찢김으로 반입 반려 후 손상 보고서 제출.',
    ai_summary: '측면 패널 관통과 금속 찢김이 확인되어 손상 보고서가 생성되었습니다.',
    verdict: '손상 확정 · 보고서 제출',
    detections: [
      { id: 'd1', label: '관통', confidence: 0.96, severity: 'HIGH', description: '측면 패널에 관통 손상이 있습니다.', box: { x: 42, y: 40, width: 18, height: 20 } },
      { id: 'd2', label: '금속 찢김', confidence: 0.87, severity: 'HIGH', description: '관통부 주변 금속이 찢어졌습니다.', box: { x: 36, y: 32, width: 30, height: 34 } },
    ],
    ocr: { text: 'DFSU 990276-2', confidence: 0.92, matches_manifest: true },
    report_status: 'COMPLETED',
    report_created_at: '2026-07-13T06:25:00Z',
  },
  {
    event_id: 'INS-4726',
    container_id: 'PONU 553380-1',
    captured_at: '2026-07-13T05:48:00Z',
    damage_summary: '이미지 처리 오류',
    risk_score: 0,
    risk_level: 'LOW',
    review_status: 'INFERENCE_FAILED',
    raw_image_url: IMG.clean,
    assigned_inspector: '담당자 미지정',
    ai_summary: '',
    verdict: '',
    error_message: '이미지 디코딩에 실패했습니다. 촬영 장비의 프레임이 손상되어 분석 파이프라인이 중단되었습니다. (오류 코드: IMG_DECODE_502)',
    detections: [],
    ocr: { text: '', confidence: 0.0, matches_manifest: false },
    report_status: 'FAILED',
  },
]
