import type { Inspection, ReviewStatus, RiskLevel } from './inspection-types'

const IMG = {
  dent: '/containers/container-dent.png',
  rust: '/containers/container-rust.png',
  hole: '/containers/container-hole.png',
  clean: '/containers/container-clean.png',
}

export const STATUS_META: Record<
  ReviewStatus,
  { label: string; tone: 'destructive' | 'warning' | 'info' | 'success' | 'muted' }
> = {
  MANUAL_NEEDED: { label: 'Manual Needed', tone: 'destructive' },
  AUDIT_REQUIRED: { label: 'Audit Required', tone: 'warning' },
  AUTO_OK: { label: 'Auto OK', tone: 'success' },
  DONE: { label: 'Done', tone: 'muted' },
  REPORT_PENDING: { label: 'Report Pending', tone: 'info' },
  REPORT_CREATED: { label: 'Report Created', tone: 'success' },
}

export const RISK_META: Record<RiskLevel, { label: string; tone: 'destructive' | 'warning' | 'success' }> = {
  HIGH: { label: 'High', tone: 'destructive' },
  MEDIUM: { label: 'Medium', tone: 'warning' },
  LOW: { label: 'Low', tone: 'success' },
}

export const mockInspections: Inspection[] = [
  {
    id: 'INS-4821',
    containerId: 'MSKU 774213-6',
    capturedAt: '2026-07-13T08:42:00Z',
    detectedDamage: 'Puncture + torn side panel',
    riskScore: 94,
    riskLevel: 'HIGH',
    status: 'MANUAL_NEEDED',
    originalImage: IMG.hole,
    lane: 'Gate A · Lane 2',
    inspector: 'Unassigned',
    detections: [
      { id: 'd1', label: 'Puncture', confidence: 0.97, severity: 'HIGH', box: { x: 41, y: 38, width: 20, height: 22 } },
      { id: 'd2', label: 'Torn metal', confidence: 0.89, severity: 'HIGH', box: { x: 34, y: 30, width: 34, height: 38 } },
      { id: 'd3', label: 'Surface scrape', confidence: 0.74, severity: 'MEDIUM', box: { x: 12, y: 58, width: 18, height: 12 } },
    ],
    ocr: { text: 'MSKU 774213-6', confidence: 0.93, matchesManifest: true },
    reportStatus: 'NOT_STARTED',
  },
  {
    id: 'INS-4818',
    containerId: 'TCLU 550918-2',
    capturedAt: '2026-07-13T08:31:00Z',
    detectedDamage: 'Major dent — end panel',
    riskScore: 88,
    riskLevel: 'HIGH',
    status: 'MANUAL_NEEDED',
    originalImage: IMG.dent,
    lane: 'Gate A · Lane 1',
    inspector: 'Unassigned',
    detections: [
      { id: 'd1', label: 'Structural dent', confidence: 0.95, severity: 'HIGH', box: { x: 30, y: 28, width: 40, height: 42 } },
      { id: 'd2', label: 'Corner deformation', confidence: 0.81, severity: 'MEDIUM', box: { x: 62, y: 60, width: 20, height: 20 } },
    ],
    ocr: { text: 'TCLU 550918-2', confidence: 0.9, matchesManifest: true },
    reportStatus: 'NOT_STARTED',
  },
  {
    id: 'INS-4805',
    containerId: 'HLXU 209471-0',
    capturedAt: '2026-07-13T08:05:00Z',
    detectedDamage: 'Heavy corrosion — door seam',
    riskScore: 79,
    riskLevel: 'HIGH',
    status: 'AUDIT_REQUIRED',
    originalImage: IMG.rust,
    lane: 'Gate B · Lane 4',
    inspector: 'M. Okafor',
    detections: [
      { id: 'd1', label: 'Corrosion cluster', confidence: 0.88, severity: 'HIGH', box: { x: 55, y: 20, width: 26, height: 52 } },
      { id: 'd2', label: 'Paint peeling', confidence: 0.72, severity: 'MEDIUM', box: { x: 20, y: 40, width: 22, height: 30 } },
    ],
    ocr: { text: 'HLXU 209471-0', confidence: 0.86, matchesManifest: false },
    reportStatus: 'NOT_STARTED',
  },
  {
    id: 'INS-4799',
    containerId: 'OOLU 118253-4',
    capturedAt: '2026-07-13T07:52:00Z',
    detectedDamage: 'Dent + surface scrape',
    riskScore: 66,
    riskLevel: 'MEDIUM',
    status: 'AUDIT_REQUIRED',
    originalImage: IMG.dent,
    lane: 'Gate B · Lane 3',
    inspector: 'M. Okafor',
    detections: [
      { id: 'd1', label: 'Dent', confidence: 0.83, severity: 'MEDIUM', box: { x: 36, y: 34, width: 30, height: 30 } },
      { id: 'd2', label: 'Scrape', confidence: 0.69, severity: 'LOW', box: { x: 15, y: 62, width: 22, height: 12 } },
    ],
    ocr: { text: 'OOLU 118253-4', confidence: 0.91, matchesManifest: true },
    reportStatus: 'NOT_STARTED',
  },
  {
    id: 'INS-4790',
    containerId: 'CMAU 663017-9',
    capturedAt: '2026-07-13T07:40:00Z',
    detectedDamage: 'Rust streaks — lower panel',
    riskScore: 58,
    riskLevel: 'MEDIUM',
    status: 'REPORT_PENDING',
    originalImage: IMG.rust,
    lane: 'Gate A · Lane 2',
    inspector: 'D. Alvarez',
    detections: [
      { id: 'd1', label: 'Rust streak', confidence: 0.8, severity: 'MEDIUM', box: { x: 24, y: 55, width: 48, height: 22 } },
    ],
    ocr: { text: 'CMAU 663017-9', confidence: 0.88, matchesManifest: true },
    reportStatus: 'GENERATING',
  },
  {
    id: 'INS-4782',
    containerId: 'MSCU 401552-3',
    capturedAt: '2026-07-13T07:28:00Z',
    detectedDamage: 'Corner post deformation',
    riskScore: 71,
    riskLevel: 'HIGH',
    status: 'REPORT_PENDING',
    originalImage: IMG.hole,
    lane: 'Gate C · Lane 6',
    inspector: 'D. Alvarez',
    detections: [
      { id: 'd1', label: 'Corner deformation', confidence: 0.85, severity: 'HIGH', box: { x: 60, y: 22, width: 24, height: 40 } },
      { id: 'd2', label: 'Hairline crack', confidence: 0.63, severity: 'MEDIUM', box: { x: 40, y: 50, width: 16, height: 14 } },
    ],
    ocr: { text: 'MSCU 401552-3', confidence: 0.84, matchesManifest: true },
    reportStatus: 'GENERATING',
  },
  {
    id: 'INS-4771',
    containerId: 'TGHU 882140-1',
    capturedAt: '2026-07-13T07:11:00Z',
    detectedDamage: 'Minor scuff — no structural risk',
    riskScore: 22,
    riskLevel: 'LOW',
    status: 'AUTO_OK',
    originalImage: IMG.clean,
    lane: 'Gate A · Lane 1',
    inspector: 'Auto',
    detections: [
      { id: 'd1', label: 'Surface scuff', confidence: 0.66, severity: 'LOW', box: { x: 30, y: 46, width: 18, height: 10 } },
    ],
    ocr: { text: 'TGHU 882140-1', confidence: 0.95, matchesManifest: true },
    reportStatus: 'NOT_STARTED',
  },
  {
    id: 'INS-4765',
    containerId: 'APZU 337029-8',
    capturedAt: '2026-07-13T06:58:00Z',
    detectedDamage: 'No damage detected',
    riskScore: 8,
    riskLevel: 'LOW',
    status: 'AUTO_OK',
    originalImage: IMG.clean,
    lane: 'Gate B · Lane 3',
    inspector: 'Auto',
    detections: [],
    ocr: { text: 'APZU 337029-8', confidence: 0.97, matchesManifest: true },
    reportStatus: 'NOT_STARTED',
  },
  {
    id: 'INS-4758',
    containerId: 'FSCU 720914-5',
    capturedAt: '2026-07-13T06:44:00Z',
    detectedDamage: 'Dent — reviewed & signed off',
    riskScore: 61,
    riskLevel: 'MEDIUM',
    status: 'DONE',
    originalImage: IMG.dent,
    lane: 'Gate C · Lane 5',
    inspector: 'M. Okafor',
    detections: [
      { id: 'd1', label: 'Dent', confidence: 0.82, severity: 'MEDIUM', box: { x: 34, y: 32, width: 30, height: 30 } },
    ],
    ocr: { text: 'FSCU 720914-5', confidence: 0.89, matchesManifest: true },
    reportStatus: 'NOT_STARTED',
  },
  {
    id: 'INS-4749',
    containerId: 'BEAU 156638-7',
    capturedAt: '2026-07-13T06:30:00Z',
    detectedDamage: 'Corrosion — report filed',
    riskScore: 74,
    riskLevel: 'HIGH',
    status: 'REPORT_CREATED',
    originalImage: IMG.rust,
    lane: 'Gate B · Lane 4',
    inspector: 'D. Alvarez',
    detections: [
      { id: 'd1', label: 'Corrosion cluster', confidence: 0.9, severity: 'HIGH', box: { x: 50, y: 24, width: 28, height: 48 } },
      { id: 'd2', label: 'Paint peeling', confidence: 0.71, severity: 'MEDIUM', box: { x: 18, y: 42, width: 20, height: 26 } },
    ],
    ocr: { text: 'BEAU 156638-7', confidence: 0.87, matchesManifest: true },
    reportStatus: 'READY',
  },
  {
    id: 'INS-4741',
    containerId: 'DFSU 990276-2',
    capturedAt: '2026-07-13T06:12:00Z',
    detectedDamage: 'Puncture — report filed',
    riskScore: 91,
    riskLevel: 'HIGH',
    status: 'REPORT_CREATED',
    originalImage: IMG.hole,
    lane: 'Gate A · Lane 2',
    inspector: 'M. Okafor',
    detections: [
      { id: 'd1', label: 'Puncture', confidence: 0.96, severity: 'HIGH', box: { x: 42, y: 40, width: 18, height: 20 } },
      { id: 'd2', label: 'Torn metal', confidence: 0.87, severity: 'HIGH', box: { x: 36, y: 32, width: 30, height: 34 } },
    ],
    ocr: { text: 'DFSU 990276-2', confidence: 0.92, matchesManifest: true },
    reportStatus: 'READY',
  },
  {
    id: 'INS-4730',
    containerId: 'NYKU 448120-0',
    capturedAt: '2026-07-13T05:58:00Z',
    detectedDamage: 'Minor rust — monitored',
    riskScore: 39,
    riskLevel: 'MEDIUM',
    status: 'DONE',
    originalImage: IMG.rust,
    lane: 'Gate C · Lane 6',
    inspector: 'D. Alvarez',
    detections: [
      { id: 'd1', label: 'Rust patch', confidence: 0.7, severity: 'MEDIUM', box: { x: 40, y: 50, width: 24, height: 18 } },
    ],
    ocr: { text: 'NYKU 448120-0', confidence: 0.9, matchesManifest: true },
    reportStatus: 'NOT_STARTED',
  },
  {
    id: 'INS-4722',
    containerId: 'SEGU 271905-4',
    capturedAt: '2026-07-13T05:41:00Z',
    detectedDamage: 'No damage detected',
    riskScore: 12,
    riskLevel: 'LOW',
    status: 'AUTO_OK',
    originalImage: IMG.clean,
    lane: 'Gate A · Lane 1',
    inspector: 'Auto',
    detections: [],
    ocr: { text: 'SEGU 271905-4', confidence: 0.96, matchesManifest: true },
    reportStatus: 'NOT_STARTED',
  },
  {
    id: 'INS-4714',
    containerId: 'WHLU 634418-9',
    capturedAt: '2026-07-13T05:26:00Z',
    detectedDamage: 'Dent + corrosion',
    riskScore: 83,
    riskLevel: 'HIGH',
    status: 'AUDIT_REQUIRED',
    originalImage: IMG.dent,
    lane: 'Gate B · Lane 3',
    inspector: 'M. Okafor',
    detections: [
      { id: 'd1', label: 'Dent', confidence: 0.86, severity: 'HIGH', box: { x: 32, y: 30, width: 34, height: 34 } },
      { id: 'd2', label: 'Corrosion', confidence: 0.77, severity: 'MEDIUM', box: { x: 60, y: 55, width: 22, height: 22 } },
    ],
    ocr: { text: 'WHLU 634418-9', confidence: 0.85, matchesManifest: false },
    reportStatus: 'NOT_STARTED',
  },
]
